name = "step"
account_id = "66ce3adbb96f6715f8cc2b04991c30e4"
compatibility_date = "2026-06-15"
main = "./worker.js"

[assets]
directory = "./dist"
binding = "ASSETS"
not_found_handling = "single-page-application"

[vars]
STEP_WEB_EXPLORER_URL = "/explorer"
STEP_WEB_MINER_URL = "/miner"
