#!/usr/bin/env node
/**
 * Extract contract ABIs from Foundry build output into
 * packages/shared-types/src/abis.ts (DEV §4.1: ABIs generated from contracts
 * and consumed by apps/services). Re-run after `forge build` on ABI changes:
 *   node scripts/dev/extract-abis.mjs
 */
import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "../..");
const contracts = [
  "StepAccess",
  "TrinityToken",
  "MeshRegistry",
  "SafetyRegistry",
  "ValidatorRegistry",
  "TriangleMiningState",
  "FoundationTreasury",
  "ProofRegistry",
  "CampaignRegistry",
  "RewardPool",
  "MiningClaimVerifier",
];

let out = `// GENERATED by scripts/dev/extract-abis.mjs from contracts/out — do not edit.\n// Regenerate after \`forge build\` when contract interfaces change.\n\n`;
for (const name of contracts) {
  const path = join(root, "contracts/out", `${name}.sol`, `${name}.json`);
  if (!existsSync(path)) {
    console.error(`missing ${path} — run \`forge build\` in contracts/ first`);
    process.exit(1);
  }
  const artifact = JSON.parse(readFileSync(path, "utf8"));
  out += `export const ${name}Abi = ${JSON.stringify(artifact.abi)} as const;\n\n`;
}
const target = join(root, "packages/shared-types/src/abis.ts");
writeFileSync(target, out);
console.log(`wrote ${target} (${contracts.length} ABIs)`);
